# Generated by Django 4.0.3 on 2022-03-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ustente',
            new_name='utente',
        ),
    ]
