# Generated by Django 4.0.3 on 2022-03-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_alter_utente_messaggio'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='email',
            field=models.CharField(max_length=100, null='false'),
            preserve_default='false',
        ),
    ]
