# Generated by Django 4.0.3 on 2022-03-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_rename_ustente_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='cognome',
            field=models.CharField(max_length=50, null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='utente',
            name='messaggio',
            field=models.CharField(max_length=300, null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='utente',
            name='nome',
            field=models.CharField(max_length=50, null='false'),
            preserve_default='false',
        ),
    ]
